### ISSUE TITLE
Build Failed Using Latest Docker Image

### ISSUE THREAD

**Issue by knkrth** [rubykube/microkube#119]
Hi, Everything works fine without editing the [app.yml](https://github.com/rubykube/microkube/blob/master/config/app.yml) file. 

When I change the value on [app.yml#L9](https://github.com/rubykube/microkube/blob/master/config/app.yml#L9) to `peatio: rubykube/peatio:latest` And run `rake service:all` build fail

```
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker-compose run --rm barong bash -c "./...]
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/file_utils.rb:57:in `sh'
lib/tasks/service.rake:120:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:126:in `block (2 levels) in <top (required)>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/gsrwallet/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
lib/tasks/service.rake:206:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:223:in `block (2 levels) in <top (required)>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/gsrwallet/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/rake:23:in `load'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/rake:23:in `<main>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:setup
instance-1:~/microkube$ 
```

**Comment by dmorales740** [comment]
Hi,
I was having the same issue after updating the image. I was able to work around it by adding a permission in the './config/barong/seeds.yml' file:

permissions:
  - { role: admin, verb: all, path: api/v2, action: accept }

It looks like now barong also fetches the permissions as well as the seeded users and levels. However, there are no permissions to fetch by default in the ./config/barong/seeds.yml' file, so it throws the error.
I Hope that helpes.

**Comment by knkrth** [comment]
Thanks, I'll try it out & let you know.

**Comment by knkrth** [comment]
It works, Thank you.
